const server =require('./http-module')
const server2 =require("./studentID")
const server3 =require("./http-content")
server.server.listen(5103)
server2.server.listen(4203)
server3.server.listen(4503)
